
#Default Spring Configuration

server.port=443
spring.application.name=EMASS AI v2
server.servlet.context-path=/emass


######################################################################################
#                                      HOST                                          #
# XCN1 : MariaDB, Redis, MinIO(NGINX), KAFKA, ElasticSearch, MongoDB                 #
# XCN2 : MinIO(DATA), KAFKA, ElasticSearch, MongoDB                                  #
# XCN3 : MinIO(DATA), KAFKA, ElasticSearch, MongoDB                                  #
######################################################################################


######################################################################################
#                                      HTTPS                                         #
#             PW - Xcnlth99                                                          #
######################################################################################
server.http2.enabled=true
server.ssl.key-store=classpath:xcn_lth.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=Xcnlth99


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/**

jasypt.encryptor.bean=jasyptStringEncryptor

# Minio Host
spring.minio.url=http://10.10.30.5:9500
# Minio Bucket name for your application
spring.minio.bucket=emass
spring.minio.access-key=minioadmin
spring.minio.secret-key=minioadmin


######################################################################################
#                                      MariaDB                                       #
#    ENC(LJMNr1gcbdR5D0zoQsE+j9DYUP7W87Qv)                                           #
######################################################################################
spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mariadb://10.200.10.81:3306/EMASSPRO?autoReconnect=true&useSSL=false&allowMultiQueries=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=NewPassword1e3!
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=177000



#spring.sql.init.data-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/insert_data.sql
#spring.jpa.defer-datasource-initialization=true


spring.solr.driver-class-name=org.apache.solr.client.solrj.io.sql.DriverImpl
spring.solr.jdbc-url=jdbc:solr://XCN1:2181,XCN2:2181,XCN3:2181,XCN4:2181/solr?collection=edc

spring.datasource.mongodb.uri=mongodb://emassai1:27018,emassai2:27018,emassai3:27018/venus?replicaSet=shard1rs
spring.datasource.mongodb.database=venus
#spring.datasource.mongodb.database=VENUS
spring.datasource.mongodb.username=ENC(gX17SY0iOxYsBFOwB/6uBw==)
spring.datasource.mongodb.password=ENC(O9IKlQAC3+9YDvJ3xbjOxg==)

spring.cloud.config.enabled=false


db.ip=10.10.30.5
#db.ip=10.200.10.64
#db.user=root
#db.password=root99

download.monitor.fixedRate=7200000




######################################################################################
#                      ElasticSearch Configuration                            #
######################################################################################
#spring.elasticsearch.uris=xcn1:9200,xcn2:9200,xcn3:9200
spring.elasticsearch.uris=10.10.30.5:9200,10.10.30.6:9200,10.10.30.7:9200
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s
#spring.elasticsearch.username=
#spring.elasticsearch.password=

######################################################################################
#                       EMASS AI KAFKA Configuration                                #
######################################################################################
spring.kafka.bootstrap-servers= XCN1:9092,XCN2:9092,XCN3:9092
spring.kafka.listener.ack-mode= manual-immediate
spring.kafka.listener.ack-time= 500
spring.kafka.listener.concurrency = 32
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer

## checked index
kafka.checked.index = ems_ui_checked_index

######################################################################################
#                       MariaDB SQL \uC2E4\uD589\uBB38                                              #
######################################################################################

## create_table.sql,insert_data.sql,patch_data.sql

#spring.jpa.defer-datasource-initialization=true
##spring.sql.init.schema-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/create_table.sql
#spring.sql.init.data-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/patch_data.sql
#spring.sql.init.mode=always


