
#Default Spring Configuration

server.port=443
spring.application.name=EMASS AI v2
server.servlet.context-path=/emass

download.monitor.fixedRate=7200000

######################################################################################
#                                      HOST                                          #
# XCN1 : MariaDB, Redis, MinIO(NGINX), KAFKA, ElasticSearch, MongoDB                 #
# XCN2 : MinIO(DATA), KAFKA, ElasticSearch, MongoDB                                  #
# XCN3 : MinIO(DATA), KAFKA, ElasticSearch, MongoDB                                  #
######################################################################################


######################################################################################
#                                      HTTPS                                         #
#             PW - Xcnlth99                                                          #
######################################################################################
server.http2.enabled=true
server.ssl.key-store=/users/emassai/conf/xcn_lth.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=Xcnlth99
server.ssl.key-alias=xcn_lth


######################################################################################
#                              MinIO (NGINX Address)                                 #
######################################################################################
spring.minio.url=http://emassai1:9500
spring.minio.bucket=emass
spring.minio.access-key=minioadmin
spring.minio.secret-key=minioadmin


######################################################################################
#                                      MariaDB                                       #
#    ENC(LJMNr1gcbdR5D0zoQsE+j9DYUP7W87Qv)                                           #
######################################################################################
spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mariadb://emassai1:3306/EMASSAI?autoReconnect=true&useSSL=false&allowMultiQueries=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=NewPassword1e3!
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=177000




######################################################################################
#                                      MongoDB                                       #
######################################################################################
spring.datasource.mongodb.uri = mongodb://emassai1:27018,emassai2:27018,emassai3:27018/venus?replicaSet=shard1rs&readPreference=primary&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000
spring.datasource.mongodb.database=venus
#spring.datasource.mongodb.username=ENC(gX17SY0iOxYsBFOwB/6uBw==)
#spring.datasource.mongodb.password=ENC(O9IKlQAC3+9YDvJ3xbjOxg==)


######################################################################################
#                       EMASS AI KAFKA Configuration                                 #
######################################################################################
spring.kafka.bootstrap-servers= emassai1:9092,emassai2:9092,emassai3:9092
spring.kafka.listener.ack-mode= manual-immediate
spring.kafka.listener.ack-time= 500
spring.kafka.listener.concurrency = 32
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer
kafka.checked.index = ems_ui_checked_index


######################################################################################
#                             ElasticSearch Configuration                            #
######################################################################################
spring.elasticsearch.uris=xcn1:19200,xcn2:19200,xcn3:19200
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s
#spring.elasticsearch.username=
#spring.elasticsearch.password=



######################################################################################
#                      Application Configuration                                     #
######################################################################################
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
server.tomcat.max-http-form-post-size=-1
server.tomcat.resource.allow-caching=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=1GB
spring.main.banner-mode=log
spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/**
spring.cloud.config.enabled=false
spring.web.resources.cache.period=3600
jasypt.encryptor.bean=jasyptStringEncryptor


######################################################################################
#                       MariaDB SQL \uC2E4\uD589\uBB38                                              #
######################################################################################

## create_table.sql,insert_data.sql,patch_data.sql

#spring.jpa.defer-datasource-initialization=true
##spring.sql.init.schema-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/create_table.sql
#spring.sql.init.data-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/patch_data.sql
#spring.sql.init.mode=always


