#Default Spring Configuration
server.port=80
spring.application.name=EMASS LTH v2
server.servlet.context-path=/venus
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
server.tomcat.max-http-form-post-size=-1
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=1GB
spring.main.banner-mode=log
spring.main.allow-circular-references=true

#http(s) 2 버전 적용
#HTTP/2.0 을 사용하기 위해서는 SSL 적용이 필수
#SSL 미 적용 시 2.0 사용되지 않음
#server.http2.enabled=true

#https 적용
#릴리즈 시 인증서 별도 생성 과정 필요 ( 메뉴얼 작성 필요 )
#적용 인증서 PW - Xcnlth99
#server.ssl.key-store=classpath:xcn_lth.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=ENC(QbvJ+la9rlY2fHKPw8KP3BgpXBnqf5w4)
#server.ssl.key-alias=xcn_lth
#--------------jhkang test properties------------
#server.ssl.key-store=xcntest.pkcs12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=Xcn1e3!
#server.ssl.key-alias=xcntest

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/**

jasypt.encryptor.bean=jasyptStringEncryptor


spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mariadb://10.200.10.81:3306/EMASSPRO?autoReconnect=true&useSSL=false&allowMultiQueries=true
spring.datasource.hikari.username=ENC(/lbmt4fxtTmWkZlofxdlKg==)
spring.datasource.hikari.password=ENC(LJMNr1gcbdR5D0zoQsE+j9DYUP7W87Qv)

spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/create_table.sql
spring.sql.init.data-locations=classpath*:com/xcurenet/sqlmap/mappers/sql/insert_data.sql
#spring.jpa.defer-datasource-initialization=true

#spring.datasource.schema=classpath*:schema/create_table.sql,classpath*:schema/patch_data.sql
#spring.datasource.data=classpath*:schema/insert_data.sql


spring.solr.driver-class-name=org.apache.solr.client.solrj.io.sql.DriverImpl
spring.solr.jdbc-url=jdbc:solr://XCN1:2181,XCN2:2181,XCN3:2181,XCN4:2181/solr?collection=edc

spring.datasource.mongodb.uri = mongodb://10.200.10.64:27018,10.200.10.65:27018,10.200.10.66:27018/venus?replicaSet=rs0&readPreference=primary&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000
#spring.datasource.mongodb.uri = mongodb://10.200.10.64:27018,10.200.10.65:27018,10.200.10.66:27018
#spring.datasource.mongodb.uri = mongodb://10.200.10.64:27018,10.200.10.65:27018,10.200.10.66:27018,10.200.10.67:27018
#spring.datasource.mongodb.uri = mongodb://1.225.49.107:27017
spring.datasource.mongodb.database=venus
#spring.datasource.mongodb.database=VENUS
spring.datasource.mongodb.username=ENC(gX17SY0iOxYsBFOwB/6uBw==)
spring.datasource.mongodb.password=ENC(O9IKlQAC3+9YDvJ3xbjOxg==)

spring.cloud.config.enabled=false


system.account = system

#url.path=/users/emasslth/makeinfo/nolog_url.json
#url.backup.path=/users/emasslth/makeinfo/backup/
#
#decoder.conf.path=/users/las/conf

#Scheduler Config
scheduler.pool.size=15

## REST TEMPLATE CONFIGURATION
# connection timeout (ms)
restapi.connection.timeout=5000
# read timeout (ms)
restapi.read.timeout=300000
# connection pool max size
restapi.connect.limit=100
# IP, Port 1 per route
restapi.max.perroute=5

#db.ip=10.200.10.81
db.ip=10.200.10.64
db.user=root
db.password=root99

#solr.servers=http://10.200.10.64:8983/solr,http://10.200.10.65:8983/solr,http://10.200.10.66:8983/solr,http://10.200.10.67:8983/solr
solr.servers=http://10.200.10.81:8983/solr,http://10.200.10.82:8983/solr,http://10.200.10.83:8983/solr
#solr.servers=http://10.10.50.62:8983/solr
solr.collection.emass=edc
solr.collection.checked=checked

ui.tmp.path=/users/lthv2/tmp/

edc.devices = XCN1,XCN2,XCN3,XCN4

download.monitor.fixedRate=7200000