CREATE DATABASE IF NOT EXISTS EMASSPRO DEFAULT CHARACTER SET=utf8;
USE EMASSPRO;

## my.cnf 등록 해야 함.
set @@group_concat_max_len = 50240;
set @@sort_buffer_size = 924288;
 
CREATE TABLE IF NOT EXISTS UI_ADMIN(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
ADMIN_NAME  VARCHAR(255)  NOT NULL    COMMENT '이름',
ADMIN_PW  VARCHAR(128)  NOT NULL    COMMENT '패스워드',
ADMIN_EMAIL  VARCHAR(600)  NULL    COMMENT '이메일',
ADMIN_HP  VARCHAR(50)  NULL    COMMENT '전화번호',
PW_CHG_DT  DATETIME  NULL    COMMENT '패스워드 변경일',
LAST_LOGIN_DT  DATETIME  NULL    COMMENT '최종 로그인 일자',
LAST_LOGIN_IP  VARCHAR(64)  NULL    COMMENT '최종 로그인 아이피',
STATUS  CHAR(1)  NULL  DEFAULT 'S'  COMMENT '상태코드 S:정상, P:패스워드 만, L:장기 미사용, C:패스워드 횟수초과, D:삭제',
WORK_STATUS  CHAR(1)  NULL  DEFAULT 'S'  COMMENT '상태코드 R:퇴직, O:휴직',
FIRSTADMIN_YN  CHAR(1)  NOT NULL  DEFAULT 'N'  COMMENT 'Y:최초 운용자, N:추가된 운용자',
ADMIN_TYPE  CHAR(1)  NULL  DEFAULT 'M'  COMMENT 'S:시스템 운용자, M:모니터링 운용자, D:장비 상태 모니터링 운용자',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용여부',
ACCESS_FAIL_CNT  INT(2)  NULL  DEFAULT '0'  COMMENT '패스워드 실패 횟수',
ACCESS_FAIL_DT  DATETIME  NULL    COMMENT '패스워드 실패 일자',
APPROBATOR  CHAR(1)  NULL  DEFAULT 'N'  COMMENT '동의서 승인권자',
INFO_FEEDBACK  CHAR(1)  NULL  DEFAULT 'N'  COMMENT '정보분류/피드백',
COMMENT  VARCHAR(500)  NULL    COMMENT '사용목적',
CREATE_DT  DATETIME  NULL    COMMENT '생성일',
RESIGN_DT datetime DEFAULT NULL  COMMENT '퇴직',
LEAVE_DT datetime DEFAULT NULL  COMMENT '휴직',
LOGIN_TYPE	CHAR(1) DEFAULT 'C' COMMENT '접속 로그인 방식',
PRIMARY KEY (ADMIN_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 정보';

CREATE TABLE IF NOT EXISTS `UI_ADMIN_XROOTMTR` (
  `ADMIN_ID` varchar(50) NOT NULL COMMENT '운용자 아이디',
  `XROOTMTR` varchar(255) NOT NULL,
  `MSGID` varchar(120) NOT NULL,
  `SRCIP` varchar(20) NOT NULL COMMENT '사용자 IP',
  PRIMARY KEY (`ADMIN_ID`,`XROOTMTR`,`SRCIP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 채팅방 마지막 포지션';



CREATE TABLE IF NOT EXISTS UI_ADMIN_ACCESS_IP(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
ACCESS_IP  VARCHAR(64)  NOT NULL    COMMENT '운용자 접근권한 IP',
PRIMARY KEY (ADMIN_ID, ACCESS_IP)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 접근권한 IP';



CREATE TABLE IF NOT EXISTS UI_SYSTEM_IPMAC(
ACCESS_IP  VARCHAR(64)  NOT NULL    COMMENT 'SYSTEM IP',
ACCESS_MAC  VARCHAR(64)  NOT NULL    COMMENT 'SYSTEM MAC',
PRIMARY KEY (ACCESS_IP, ACCESS_MAC)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SYSTEM IP/MAC';



CREATE TABLE IF NOT EXISTS UI_ADMIN_CO(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
COCD  VARCHAR(20)  NOT  NULL    COMMENT '회사 코드',
SORT  INT(11)  NULL    COMMENT '정렬 순서',
PRIMARY KEY (ADMIN_ID, COCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 회사 권한';



CREATE TABLE IF NOT EXISTS UI_ADMIN_BUSI(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
BUSICD  VARCHAR(20)  NOT NULL    COMMENT '사업장 코드',
SORT  INT(11)  NOT NULL    COMMENT '정렬 순서',
PRIMARY KEY (ADMIN_ID, BUSICD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 사업장 권한';

/*
CREATE TABLE IF NOT EXISTS UI_ADMIN_DEPT(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
DEPTCD  VARCHAR(20)  NOT NULL    COMMENT '부서 코드',
SORT  INT(11)  NOT NULL    COMMENT '정렬 순서',
PRIMARY KEY (ADMIN_ID, DEPTCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 부서 권한';
*/

CREATE TABLE IF NOT EXISTS UI_ADMIN_SERVICE(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
SERVICECD  VARCHAR(10)  NOT NULL    COMMENT '서비스 코드',
PRIMARY KEY (ADMIN_ID, SERVICECD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 서비스 타입 권한';

CREATE TABLE IF NOT EXISTS UI_ADMIN_REGEXP(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
CODE  VARCHAR(20)  NOT NULL    COMMENT '패턴 코드',
PRIMARY KEY (ADMIN_ID, CODE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 개인정보 권한';



CREATE TABLE IF NOT EXISTS UI_ADMIN_GRID(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
GRID_ID  VARCHAR(50)  NOT NULL    COMMENT '그리드 아이디',
HEADER  LONGTEXT  NULL    COMMENT '헤더 내용',
PRIMARY KEY (ADMIN_ID, GRID_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 그리드 열설정';



CREATE TABLE IF NOT EXISTS UI_ADMIN_PW_HISTORY(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
ADMIN_PW  VARCHAR(128)  NOT NULL    COMMENT '패스워드',
UPDATE_DT  DATETIME  NOT NULL    COMMENT '헤더 내용',
PRIMARY KEY (ADMIN_ID, ADMIN_PW)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 패스워드 변경 이력';

CREATE TABLE IF NOT EXISTS UI_ADMIN_GENERATE (
  ADMIN_ID VARCHAR(50) NOT NULL COMMENT '운용자 아이디',
  ADMIN_GENERATE VARCHAR(100) NOT NULL COMMENT '구글 OTP 개인키',
  PRIMARY KEY (ADMIN_ID)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자별 구글 OTP 개인키';

CREATE TABLE IF NOT EXISTS UI_REGEXP(
CODE  varchar(255)  NOT NULL    COMMENT '패턴 코드',
NAME  VARCHAR(255)  NOT NULL    COMMENT '패턴 이름',
REGEX  VARCHAR(255)  NULL    COMMENT '패턴 정규식',
PRIMARY KEY (CODE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='패턴 코드';



CREATE TABLE IF NOT EXISTS UI_CO(
COCD  VARCHAR(20)  NOT NULL    COMMENT '회사 코드',
CONM  VARCHAR(60)  NOT NULL    COMMENT '회사 이름',
PRIMARY KEY (COCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회사 코드';



CREATE TABLE IF NOT EXISTS UI_BUSI(
BUSICD  VARCHAR(20)  NOT NULL    COMMENT '사업장 코드',
BUSINM  VARCHAR(64)  NOT NULL    COMMENT '사업장 이름',
COCD  VARCHAR(20)  NOT NULL    COMMENT '회사 코드',
PRIMARY KEY (BUSICD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사업장 코드';



CREATE TABLE IF NOT EXISTS UI_GENERAL(
GENERALCD  VARCHAR(20)  NOT NULL    COMMENT '총괄 코드',
GENERALNM  VARCHAR(60)  NOT NULL    COMMENT '총괄 이름',
COCD  VARCHAR(20)  NOT NULL    COMMENT '회사 코드',
PRIMARY KEY (GENERALCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='총괄 코드';



CREATE TABLE IF NOT EXISTS UI_DEPT(
DEPTCD  VARCHAR(20)  NOT NULL    COMMENT '부서 코드',
DEPTNM  VARCHAR(256)  NOT NULL    COMMENT '부서 이름',
PDEPTCD  VARCHAR(20)  NULL    COMMENT '상위 부서 코드',
COCD  VARCHAR(20)  NOT NULL    COMMENT '회사 코드',
PRIMARY KEY (DEPTCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부서 코드';



CREATE TABLE IF NOT EXISTS UI_JIKGUB(
JIKGUBCD  VARCHAR(20)  NOT NULL    COMMENT '직급 코드',
JIKGUBNM  VARCHAR(64)  NOT NULL    COMMENT '직급 이름',
PRIMARY KEY (JIKGUBCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='직급 코드';



CREATE TABLE IF NOT EXISTS UI_JIKIN(
JIKINCD  VARCHAR(20)  NOT NULL    COMMENT '재직 코드',
JIKINNM  VARCHAR(64)  NOT NULL    COMMENT '재직 이름',
PRIMARY KEY (JIKINCD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT=' 재직 코드';



CREATE TABLE IF NOT EXISTS UI_SERVICE(
SERVICECD		VARCHAR(10) 	NOT NULL	COMMENT '서비스 코드',
SERVICENM_LV1	VARCHAR(200) 	NULL		COMMENT '서비스 이름(대)',
SERVICENM_LV2	VARCHAR(200) 	NULL		COMMENT '서비스 이름(중)',
SERVICENM_LV3	VARCHAR(200) 	NULL		COMMENT '서비스 이름(소)',
IN_OUT			CHAR(1)			NOT NULL	COMMENT '수/발신 타입',
SORT  			INT(11)			NULL		COMMENT '정렬 순서',
USE_YN			CHAR(1)			NOT NULL	DEFAULT 'Y'		COMMENT '사용여부',
MSGGRPCD		VARCHAR(10)		NULL		COMMENT '메신저 그룹코드',
PRIMARY KEY (SERVICECD)  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='서비스 타입';



CREATE TABLE IF NOT EXISTS UI_ATTACH(
ATTACH_TYPE  VARCHAR(20)  NOT NULL    COMMENT '첨부파일 확장자',
ATTACH_NAME  VARCHAR(300)  NOT NULL    COMMENT '첨부파일 이름',
ATTACH_DESC  VARCHAR(300)  NULL    COMMENT '첨부파일 설명',
PRIMARY KEY (ATTACH_TYPE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='첨부파일 코드';



CREATE TABLE IF NOT EXISTS UI_KEYWORD_GROUP(
GROUP_SEQ  INT(11)  NOT NULL    COMMENT '그룹 번호',
GROUP_NAME  VARCHAR(60)  NULL    COMMENT '그룹 이름',
USE_YN		CHAR(1)		NULL		COMMENT '사용여부',
PRIMARY KEY (GROUP_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='키워드 그룹';


CREATE TABLE IF NOT EXISTS UI_KEYWORD(
	KEYWORD_SEQ  INT(11)  NOT NULL  AUTO_INCREMENT  COMMENT '키워드 번호',
	KEYWORD_NAME  VARCHAR(60)  NOT NULL    COMMENT '키워드',
	GROUP_SEQ  INT(11)  NOT NULL    COMMENT '그룹 번호',
	KEYWORD_DESC  VARCHAR(1024)  NULL    COMMENT '키워드 설명',
PRIMARY KEY (KEYWORD_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='키워드(예약어)';



CREATE TABLE IF NOT EXISTS UI_USERS(
USER_ID  VARCHAR(250)  NOT NULL    COMMENT '아이디',
SABUN varchar(250) DEFAULT NULL COMMENT '사번',
USER_NM  VARCHAR(255)  NOT NULL    COMMENT '이름',
COCD  VARCHAR(20)  NULL    COMMENT '회사 코드',
GENERALCD  VARCHAR(20)  NULL    COMMENT '총괄 코드',
BUSICD  VARCHAR(20)  NULL    COMMENT '사업장 코드',
DEPTCD  VARCHAR(20)  NULL    COMMENT '부서 코드',
JIKINCD  VARCHAR(20)  NULL    COMMENT '재직 코드',
JIKGUBCD  VARCHAR(20)  NULL    COMMENT '직급 코드',
CEO  CHAR(1)  NULL  DEFAULT 'N'  COMMENT 'CEO 여부(Y,N)',
STDT date DEFAULT NULL COMMENT '시작일',
EDDT date DEFAULT NULL COMMENT '종료일',
ASCD varchar(20) DEFAULT NULL COMMENT '제조번호',
EMAIL varchar(120) DEFAULT NULL COMMENT '이메일',
PRIMARY KEY (USER_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 정보';

CREATE TABLE IF NOT EXISTS UI_CEO (
  USER_ID VARCHAR(250) NOT NULL COMMENT '사용자 아이디',
  PRIMARY KEY (USER_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ceo 정보';


CREATE TABLE IF NOT EXISTS UI_USER_IP(
USER_ID  VARCHAR(250)  NOT NULL    COMMENT '아이디',
USER_IP  VARCHAR(64)  NOT NULL    COMMENT 'IP',
PRIMARY KEY (USER_ID, USER_IP)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 IP 정보';



CREATE TABLE IF NOT EXISTS UI_USER_EMAIL(
USER_ID  VARCHAR(250)  NOT NULL    COMMENT '아이디',
USER_EMAIL  VARCHAR(250)  NOT NULL    COMMENT '이메일',
PRIMARY KEY (USER_ID, USER_EMAIL)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 EMAIL 정보';


CREATE TABLE IF NOT EXISTS UI_BUSI_IPRANGE(
BUSICD  VARCHAR(20)  NOT NULL    COMMENT '사업장 코드',
START_IP  VARCHAR(64) NOT  NULL    COMMENT '시작 아이피',
END_IP  VARCHAR(64)  NOT  NULL    COMMENT '끝 아이피',
COMMENT  VARCHAR(500)  NULL    COMMENT '설명',
CREATE_DT  DATETIME  NULL    COMMENT '생성일',
PRIMARY KEY (BUSICD, START_IP, END_IP)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사업장 내부 아이피';


CREATE TABLE IF NOT EXISTS UI_DEPT_IPRANGE(
DEPTCD  varchar(20)  NOT NULL    COMMENT '부서 코드',
START_IP  varchar(64)  NOT NULL    COMMENT '시작 아이피',
END_IP  varchar(64)  NOT NULL    COMMENT '끝 아이피',
COMMENT  varchar(500)  NULL    COMMENT '설명',
CREATE_DT  datetime  NULL    COMMENT '생성일',
PRIMARY KEY (DEPTCD, START_IP, END_IP)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부서 내부 아이피';

CREATE TABLE IF NOT EXISTS UI_ID_NOLOG(
ID_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'ID 미로깅 일련번호',
SERVICECD  VARCHAR(10)  NOT NULL    COMMENT '서비스 타입',
USER_ID  VARCHAR(250)  NOT NULL    COMMENT '사용자 ID',
CREATE_USER varchar(30) DEFAULT NULL COMMENT '작성자',
CREATE_DT  DATETIME  NULL    COMMENT '작성일',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용 여부(Y:사용, N:사용안함(삭제) )',
PRIMARY KEY (ID_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='서비스타입 별 ID 미로깅';



CREATE TABLE IF NOT EXISTS UI_SIZE_LOG(
SIZE_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'SIZE 로깅 일련번호',
SERVICECD  VARCHAR(10)  NOT NULL    COMMENT '서비스 타입',
LOWSIZE  INT(11)  NOT NULL    COMMENT '하한값',
HIGHSIZE  INT(11)  NOT NULL    COMMENT '상한값',
SIZE_CONDITION  CHAR(1)  NULL    COMMENT '조건(범위:B, 이상:L, 이하:S)',
CREATE_USER varchar(30) DEFAULT NULL COMMENT '작성자',
CREATE_DT  DATETIME  NULL    COMMENT '작성일',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용 여부(Y:사용, N:사용안함(삭제) )',
PRIMARY KEY (SIZE_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='메시지 크기 별 로깅';



CREATE TABLE IF NOT EXISTS UI_DOMAIN_NOLOG(
DOMAIN_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'DOMAIN 미로깅 일련번호',
SERVICECD  VARCHAR(10)  NOT NULL    COMMENT '서비스 타입',
DOMAIN  VARCHAR(128)  NOT NULL    COMMENT 'DOMAIN',
CREATE_USER varchar(30) DEFAULT NULL COMMENT '작성자',
CREATE_DT  DATETIME  NULL    COMMENT '작성일',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용 여부(Y:사용, N:사용안함(삭제) )',
PRIMARY KEY (DOMAIN_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='서비스타입 별 DOMAIN 미로깅';


CREATE TABLE IF NOT EXISTS UI_IP_NOLOG(
IP_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'IP 미로깅 일련번호',
USER_IP_ALL  CHAR(1)  NULL    COMMENT '사용자 IP 전체 선택여부(Y:전체선택, N:범위 입력)',
USER_S_IP  VARCHAR(64)  NOT NULL    COMMENT '사용자 시작 IP',
USER_E_IP  VARCHAR(64)  NOT NULL    COMMENT '사용자 끝 IP',
USER_PORT_ALL  CHAR(1)  NULL    COMMENT '사용자 PORT 전체 선택여부(Y:전체선택, N:범위 입력)',
USER_S_PORT  INT(11)  NULL    COMMENT '사용자 시작 PORT',
USER_E_PORT  INT(11)  NULL    COMMENT '사용자 끝 PORT',
SERVER_IP_ALL  CHAR(1)  NULL    COMMENT '서버 IP 전체 선택여부(Y:전체선택, N:범위 입력)',
SERVER_S_IP  VARCHAR(64)  NOT NULL    COMMENT '서버 시작 IP',
SERVER_E_IP  VARCHAR(64)  NOT NULL    COMMENT '서버 끝 IP',
SERVER_PORT_ALL  CHAR(1)  NULL    COMMENT '서버 PORT 전체 선택여부(Y:전체선택, N:범위 입력)',
SERVER_S_PORT  INT(11)  NOT NULL    COMMENT '서버 시작 PORT',
SERVER_E_PORT  INT(11)  NOT NULL    COMMENT '서버 끝 PORT',
COMMENT  VARCHAR(256)  NULL    COMMENT '설명',
CREATE_USER varchar(30) DEFAULT NULL COMMENT '작성자',
CREATE_DT  DATETIME  NULL    COMMENT '작성일',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용 여부(Y:사용, N:사용안함(삭제) )',
FILTER_IDX int(11) unsigned DEFAULT NULL COMMENT 'IP FILTER OID',
PRIMARY KEY (IP_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='IP 미로깅';


CREATE TABLE IF NOT EXISTS UI_IP_NOLOG_DEVICE(
DEVICE_SEQ  INT(11)  NOT NULL    COMMENT '장비 일련번호',
IP_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'IP 미로깅 일련번호',
VERSION  INT(11)  NOT NULL    COMMENT 'IP 미로깅 버전',
RUTIME  DATETIME  NOT NULL    COMMENT '필터 적용일',
PRIMARY KEY (DEVICE_SEQ, IP_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='IP 미로깅 장비 매핑';


CREATE TABLE IF NOT EXISTS UI_URL_NOLOG(
URL_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'URL 미로깅 일련번호',
URL  VARCHAR(128)  NOT NULL    COMMENT 'URL',
CREATE_USER varchar(30) DEFAULT NULL COMMENT '작성자',
CREATE_DT  DATETIME  NULL    COMMENT '작성일',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용 여부(Y:사용, N:사용안함(삭제) )',
PRIMARY KEY (URL_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='URL 미로깅';


CREATE TABLE IF NOT EXISTS UI_SUBJECT_NOLOG(
SUBJECT_LOG_SEQ  INT(11)  NOT NULL    COMMENT '제목 미로깅 일련번호',
SERVICECD  VARCHAR(10)  NOT NULL    COMMENT '서비스 타입',
SUBJECT  VARCHAR(256)  NOT NULL    COMMENT '제목',
CREATE_USER varchar(30) DEFAULT NULL COMMENT '작성자',
CREATE_DT  DATETIME  NULL    COMMENT '작성일',
USE_YN  CHAR(1)  NOT NULL  DEFAULT 'Y'  COMMENT '사용 여부(Y:사용, N:사용안함(삭제) )',
PRIMARY KEY (SUBJECT_LOG_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SUBJECT 미로깅';


CREATE TABLE IF NOT EXISTS UI_CONF(
CONF_ID  VARCHAR(255)  NOT NULL    COMMENT '설정 코드',
VAL  LONGTEXT  CHARACTER SET utf8 NULL    COMMENT '설정 값',
DEFAULT_VAL  VARCHAR(55)  NULL    COMMENT '기본 값',
UPDATE_DT  DATETIME  NOT NULL    COMMENT '수정 일',
PRIMARY KEY (CONF_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI 설정';



CREATE TABLE IF NOT EXISTS UI_CONF_ADMIN(
CONF_ID  VARCHAR(255)  NOT NULL    COMMENT '설정 코드',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '아이디',
VAL  LONGTEXT  CHARACTER SET utf8 NULL    COMMENT '설정 값',
DEFAULT_VAL  VARCHAR(55)  NULL    COMMENT '기본 값',
UPDATE_DT  DATETIME  NOT NULL    COMMENT '수정 일',
PRIMARY KEY (CONF_ID, ADMIN_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI 운용자 별 설정';



CREATE TABLE IF NOT EXISTS UI_CONSENT(
NO  VARCHAR(30)  NOT NULL    COMMENT '동의서 번호',
TYPE  VARCHAR(256)  NULL    COMMENT '동의서 유형',
NAME  VARCHAR(255)  NULL    COMMENT '성명',
USER_ID  VARCHAR(50)  NULL    COMMENT '사용자 아이디',
DEPTCD  VARCHAR(20)  NULL    COMMENT '부서 코드',
DEPTNM  VARCHAR(60)  NULL    COMMENT '부서 이름',
EXPIRATION_DT  DATETIME  NULL    COMMENT '유효기간',
ATTACHED_YN  CHAR(1)  NULL    COMMENT '첨부파일 등록 여부',
SEARCH_YN  CHAR(1)  NULL    COMMENT '조회 여부',
CREATE_DT  DATETIME  NULL    COMMENT '등록일',
CREATE_ID  VARCHAR(50)  NULL    COMMENT '등록 아이디',
CREATE_NAME  VARCHAR(50)  NULL    COMMENT '등록 이름',
PURPOSE  VARCHAR(5000)  NULL    COMMENT '조회 목적',
FILE_PATH  VARCHAR(500)  NULL    COMMENT '파일 경로',
FILE_NAME  VARCHAR(512)  NULL    COMMENT '파일 이름',
APPCD  CHAR(1)  NULL    COMMENT '승인 상태',
ALARM_YN  CHAR(1)  NULL    COMMENT '알림 사용 여부',
REGISTRANT_YN  CHAR(1)  NULL    COMMENT '알림 대상 등록자 여부',
ALARM_MAIL_YN  CHAR(1)  NULL    COMMENT '메일 알림 여부',
ALARM_SMS_YN  CHAR(1)  NULL    COMMENT 'SMS 알림 여부',
ALARM_MONITOR_YN  CHAR(1)  NULL    COMMENT '화면 알림 여부',
PRIMARY KEY (NO)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='동의서';






CREATE TABLE IF NOT EXISTS UI_CONSENT_IP(
NO  VARCHAR(30)  NOT NULL    COMMENT '동의서 번호',
IP  VARCHAR(64)  NOT NULL    COMMENT '동의서 IP',
PRIMARY KEY (NO, IP)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='동의서 IP';



CREATE TABLE IF NOT EXISTS UI_CONSENT_SEQ(
NO  INT(6)  NOT NULL    COMMENT '동의서 앞 날짜',
CURRENT_DT  DATETIME  NOT NULL    COMMENT '발급일',
PRIMARY KEY (NO, CURRENT_DT)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='동의서 시퀀스 테이블';



CREATE TABLE IF NOT EXISTS UI_DEVICE(
DEVICE_SEQ  INT(11)  NOT NULL    COMMENT '장비 일련번호',
DEVICE_IP  VARCHAR(64)  NULL    COMMENT '장비 IP',
DEVICE_NM  VARCHAR(256)  NULL    COMMENT '장비 이름',
SSH_ID		VARCHAR(256) NULL	COMMENT 'SSH 접속 아이디',
SSH_PW		VARBINARY(512) NULL	COMMENT 'SSH 접속 비밀번호',
COMMENTS  VARCHAR(512)  NULL    COMMENT '장비 설명',
DEVICE_TYPE  VARCHAR(50)  NULL    COMMENT '장비의 타입 표시(A-통합,C-분리형 수집,L-분리형 로깅, M-Hadoop 모니터링,H-Hadoop 단일노드)',
DEVICE_STATUS  CHAR(1)  NULL    COMMENT '장비 상태(S : 성공, F : 실패, T : 연결실패, D : 불일치)',
IP_NOLOG_APPLY_VERSION  INT(11)  NULL    COMMENT 'IP 필터링 룰 적용 버전',
IP_NOLOG_APPLY_DATE  DATETIME  NULL    COMMENT 'IP 필터링 룰 적용 일자',
UACS_RU_TIME  DATETIME  NULL    COMMENT 'UACS 룰 최근 갱신 일자',
UACS_RT_TIME  DATETIME  NULL    COMMENT 'UACS 룰 갱신 시도 일자',
UACS_R_STATUS  CHAR(1)  NULL    COMMENT 'UACS 최종 갱신 유무',
UACS_MU_TIME  DATETIME  NULL    COMMENT 'UACS 차단 메시지 최근 갱신 일자',
UACS_MT_TIME  DATETIME  NULL    COMMENT 'UACS 차단 메시지 갱신 시도 일자',
UACS_M_STATUS  CHAR(1)  NULL    COMMENT 'UACS  차단 메시지 최종 갱신 유무',
UFDB_MADE_TIME  DATETIME  NULL    COMMENT 'UFDB 적용 버전(일자)',
ADVANCE_WARN_RATE  INT(11)  NULL    COMMENT '감사증적 알림 사이즈 설정',
SERIOUS_WARN_RATE  INT(11)  NULL    COMMENT '감사증적 포화 사이즈 설정',
DELETE_WARN_RATE  INT(11)  NULL    COMMENT '감사증적 삭제 사이즈 설정',
DEVICE_HOSTKEY  VARCHAR(10)  NULL    COMMENT 'UACS RULE 통신(XML RPC) 시 키 값',
RULE_VERSION  INT(11)  NULL    COMMENT '장비 룰 적용 버전',
RULE_DATE  DATETIME  NULL    COMMENT '룰 적용일자',
USE_YN  CHAR(1)  NULL    COMMENT '장비 사용 여부',
CREATE_DT  DATETIME  NULL    COMMENT '등록 일자',
DEVICE_SYS_EID int(11) DEFAULT NULL COMMENT '장비 EID',
PRIMARY KEY (DEVICE_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='장비관리';


CREATE TABLE IF NOT EXISTS UI_DEVICE_TRAFFIC_STAT(
DEVICE_SEQ  INT(11)  NOT NULL    COMMENT '장비 일련번호',
UPDATE_DT  DATETIME  NOT NULL    COMMENT '최종 업데이트 날짜',
PORT  VARCHAR(20)  NOT NULL    COMMENT '포트정보',
DIRECTION  CHAR(1)  NOT NULL    COMMENT '방향성 (0:수신, 1:발신)',
HOUR_SIZE  BIGINT(20)  NULL    COMMENT '1시간 동안 쌓인 트래픽 사이즈(MBytpe)',
HOUR_CNT  BIGINT(20)  NULL    COMMENT '1시간 동안 쌓인 트래픽 건수',
INSERT_DT  DATETIME  NULL    COMMENT '최초 등록 날짜',
PRIMARY KEY (DEVICE_SEQ, UPDATE_DT, PORT, DIRECTION)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='장비 IIF TRAFFIC 통계';



CREATE TABLE IF NOT EXISTS UI_DASHBOARD_ADMIN(
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
DASH_KEY  VARCHAR(50)  NOT NULL    COMMENT '',
DASH_VAL  VARCHAR(10)  NULL    COMMENT '',
ORDER_ROW  INT(11)  NULL    COMMENT '차트 순서',
ORDER_COL  INT(11)  NULL    COMMENT '',
DASH_CLASS  VARCHAR(30)  NULL    COMMENT '색상',
DASH_ICON  VARCHAR(30)  NULL    COMMENT '아이콘 코드',
PRIMARY KEY (ADMIN_ID,DASH_KEY)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI 대시보드 설정';



CREATE TABLE IF NOT EXISTS UI_DASHBOARD(
DASH_KEY  VARCHAR(50)  NOT NULL    COMMENT '',
DASH_VAL  VARCHAR(10)  NULL    COMMENT '',
ORDER_ROW  INT(11)  NULL    COMMENT '차트 순서',
ORDER_COL  INT(11)  NULL    COMMENT '',
DASH_CLASS  VARCHAR(30)  NULL    COMMENT '색상',
DASH_ICON  VARCHAR(30)  NULL    COMMENT '아이콘 코드',
PRIMARY KEY (DASH_KEY)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI 대시보드 설정';


CREATE TABLE IF NOT EXISTS UI_HDFS_SIZE(
DATE datetime NOT NULL COMMENT '날짜',
REMAINING varchar(20) DEFAULT NULL COMMENT '남은 용량',
USED varchar(20) DEFAULT NULL COMMENT '사용중인 용량',
TOTAL varchar(20) DEFAULT NULL COMMENT '전체 용량',
USED_PERCENT varchar(20) DEFAULT NULL COMMENT '사용중인 용량 %',
PRIMARY KEY (DATE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='대시보드 일별 수집 데이터 용량';


CREATE TABLE IF NOT EXISTS UI_HDFS_DIR_SIZE(
DATE datetime NOT NULL COMMENT '날짜',
TOTAL varchar(20) DEFAULT NULL COMMENT '용량',
PRIMARY KEY (DATE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='대시보드 일별 첨부 용량';



CREATE TABLE IF NOT EXISTS XCNLOG(
SEQ  INT(11) unsigned  NOT NULL    COMMENT '순번',
IP  VARCHAR(64)  NULL    COMMENT '장비 아이피',
CTIME  DATETIME  NULL    COMMENT '로그 발생 시각',
MODULE  VARCHAR(32)  NULL    COMMENT '모듈',
SERVICE  CHAR(1)  NULL    COMMENT '로그 구분(A:감사기능, P:프로세스, I:무결성, S:시스템)',
TYPE  CHAR(1)  NULL    COMMENT '로그 항목(S:시작, E:종료, R:작동중, X:동작안함, N:훼손, U:알림사이즈 초과, F:포화사이즈 초과, D:삭제 완료)',
INFO  VARCHAR(256)  NULL    COMMENT '비고',
PRIMARY KEY (SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='XCNLOG';


CREATE TABLE IF NOT EXISTS UI_SNMP_TRAP(
EVENT_DT  DATETIME  NOT NULL    COMMENT '이벤트 발생일',
DEVICE_IP  VARCHAR(64)  NOT NULL    COMMENT '이벤트 발생 장비 IP',
DEVISION  VARCHAR(50)  NOT NULL    COMMENT '이벤트 타입',
SEQ  INT  NOT NULL    COMMENT '일련번호',
MASTER_IP  VARCHAR(64)  NULL    COMMENT '마스터 장비 IP',
EVENT_LEVEL  CHAR(1)  NULL    COMMENT '이벤트 레벨(I:정보, W:경고, E:에러)',
TITLE  VARCHAR(256)  NULL    COMMENT '이벤트 제목',
CONTENT  LONGTEXT  NULL    COMMENT '이벤트 내용',
PRIMARY KEY (EVENT_DT,DEVICE_IP,DEVISION,SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SNMP TRAP';



CREATE TABLE IF NOT EXISTS UI_WORKDAY(
BUSICD  VARCHAR(20)  NOT NULL    COMMENT '사업장 코드',
WDAY  CHAR(7)  NULL    COMMENT '업무요일',
WHOUR  CHAR(24)  NULL    COMMENT '업무시간',
CREATE_DT  DATETIME  NULL    COMMENT '생성일',
PRIMARY KEY (BUSICD)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='업무/휴일 설정(업무일 설정)';



CREATE TABLE IF NOT EXISTS UI_HOLIDAY(
BUSICD  VARCHAR(20)  NOT NULL    COMMENT '사업장 코드',
DATE  DATETIME  NOT NULL    COMMENT '날짜',
COMMENT  VARCHAR(150)  NULL    COMMENT '설명',
CREATE_DT  DATETIME  NULL    COMMENT '생성일',
PRIMARY KEY (BUSICD, DATE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='업무/휴일 설정(휴일 설정)';


CREATE TABLE IF NOT EXISTS UI_USAGE_COMPARE(
  CTIME char(10) NOT NULL COMMENT '발생 시간',
  DATE_MONTH char(6) CHARACTER SET latin1 NOT NULL COMMENT '발생 시간 - 년월',
  DATE_DAY char(2) CHARACTER SET latin1 NOT NULL COMMENT '발생 시간 - 일',
  DATE_TIME char(2) CHARACTER SET latin1 NOT NULL COMMENT '발생 시간 - 시간',
  DATE_DAY_OF_WEEK tinyint(4) unsigned NOT NULL,
  DATE_WEEK_OF_MONTH tinyint(4) unsigned NOT NULL COMMENT '발생 시간 - 주',
  IN_MAIL int(10) unsigned NOT NULL COMMENT '내부메일수',
  OUT_MAIL int(10) unsigned NOT NULL COMMENT '외부메일수',
  FILE_SIZE bigint(20) unsigned NOT NULL COMMENT '입력파일크기(byte)',
  FTP bigint(20) unsigned NOT NULL COMMENT 'FTP IN/OUT 크기(byte)',
  TOTAL_SIZE bigint(20) unsigned NOT NULL COMMENT '전체 크기(byte)',
PRIMARY KEY (CTIME)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI 시간단위 사용량';


CREATE TABLE IF NOT EXISTS UI_INTEREST_USERS(
USER_SEQ  INT(11)  NOT NULL    COMMENT '관심 사용자 일련번호',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
USER_TYPE  CHAR(1)  NULL    COMMENT '사용자 타입(기존 사용자:E, 직접등록:I)',
USER_NM  VARCHAR(255)  NULL    COMMENT '이름',
USER_ID  VARCHAR(50)  NULL    COMMENT '아이디',
COMMENT  VARCHAR(500)  NULL    COMMENT '설명',
PRIMARY KEY (USER_SEQ, ADMIN_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='관심 사용자 정보';


CREATE TABLE IF NOT EXISTS UI_INTEREST_USER_IP(
USER_SEQ  INT(11)  NOT NULL    COMMENT '관심 사용자 일련번호',
USER_IP  VARCHAR(64)  NOT NULL    COMMENT 'IP',
PRIMARY KEY (USER_SEQ, USER_IP)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='관심 사용자 IP 정보';


CREATE TABLE IF NOT EXISTS UI_INTEREST_USER_EMAIL(
USER_SEQ  INT(11)  NOT NULL    COMMENT '관심 사용자 일련번호',
USER_EMAIL  VARCHAR(250)  NOT NULL    COMMENT '이메일',
PRIMARY KEY (USER_SEQ, USER_EMAIL)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='관심 사용자 EMAIL 정보';


CREATE TABLE IF NOT EXISTS UI_FILTER(
FILTER_SEQ  INT(11)  NOT NULL    COMMENT '필터 시퀀스',
P_FILTER_SEQ  INT(11)  NULL    COMMENT '상위 필터 시퀀스',
FILTER_NM  VARCHAR(128)  NULL    COMMENT '필터/폴더명',
FILTER_TYPE  CHAR(1)  NULL    COMMENT '필터 타입(F: FOLDER, D : FILTER DATA, Q: QUERY DATA, R: Root, U: User Root)',
FILTER_ORDER  INT(11)  NULL    COMMENT '필터 순서(정렬)',
FILTER_OPEN  VARCHAR(5)  NULL    COMMENT '필터 트리 열기/닫기',
USER_DT_CD  CHAR(1)  NULL    COMMENT '날짜 선택 조건(1:고정날짜, 2:변동날짜, 3:날짜입력)',
START_DT  VARCHAR(14)  NULL    COMMENT '검색 시작일',
END_DT  VARCHAR(14)  NULL    COMMENT '검색 종료일',
CONDITIONS  LONGTEXT  NULL    COMMENT '검색조건 값',
PRIMARY KEY (FILTER_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='기본 제공 필터 카테고리';


CREATE TABLE IF NOT EXISTS UI_FILTER_ADMIN(
FILTER_SEQ  INT(11)  NOT NULL    COMMENT '필터 시퀀스',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
P_FILTER_SEQ  INT(11)  NULL    COMMENT '상위 필터 시퀀스',
FILTER_NM  VARCHAR(128)  NULL    COMMENT '필터/폴더명',
FILTER_TYPE  CHAR(1)  NULL    COMMENT '필터 타입(F: FOLDER, D : FILTER DATA, Q: QUERY DATA, R: Root, U: User Root)',
FILTER_ORDER  INT(11)  NULL    COMMENT '필터 순서(정렬)',
FILTER_OPEN  VARCHAR(5)  NULL    COMMENT '필터 트리 열기/닫기',
USER_DT_CD  CHAR(1)  NULL    COMMENT '날짜 선택 조건(1:고정날짜, 2:변동날짜, 3:날짜입력)',
START_DT  VARCHAR(14)  NULL    COMMENT '검색 시작일',
END_DT  VARCHAR(14)  NULL    COMMENT '검색 종료일',
CONDITIONS  LONGTEXT  NULL    COMMENT '검색조건 값',
PRIMARY KEY (FILTER_SEQ, ADMIN_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 필터 카테고리';


CREATE TABLE IF NOT EXISTS `UI_FOLDER_ADMIN` (
  `FOLDER_SEQ` int(11) NOT NULL COMMENT '사용자 폴더 시퀀스',
  `ADMIN_ID` varchar(50) NOT NULL COMMENT '운용자 아이디',
  `P_FOLDER_SEQ` int(11) DEFAULT NULL COMMENT '상위 사용자 폴더 시퀀스',
  `FOLDER_NM` varchar(128) DEFAULT NULL COMMENT '사용자 폴더/폴더명',
  `FOLDER_TYPE` char(1) DEFAULT NULL COMMENT '사용자 폴더 타입(F: FOLDER, D : USER FOLDER DATA, R: Root, U: User Root)',
  `FOLDER_ORDER` int(11) DEFAULT NULL COMMENT '사용자 폴더 순서(정렬)',
  `FOLDER_OPEN` varchar(5) DEFAULT NULL COMMENT '사용자 폴더 트리 열기/닫기',
  `CONDITIONS` longtext COMMENT '검색조건 값',
  PRIMARY KEY (`FOLDER_SEQ`,`ADMIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 폴더 카테고리';

CREATE TABLE IF NOT EXISTS `UI_FOLDER_MESSAGE` (
  `FOLDER_SEQ` int(11) NOT NULL COMMENT '사용자 폴더 시퀀스',
  `MSGID` char(100) NOT NULL DEFAULT '' COMMENT '메시지 ID',
  `CONSENT_NO` char(30) DEFAULT NULL COMMENT '동의서 번호',
  PRIMARY KEY (`FOLDER_SEQ`,`MSGID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 정의 폴더 메시지';


CREATE TABLE IF NOT EXISTS UI_ALARM(
ALARM_SEQ  INT(11)  NOT NULL    COMMENT 'ALARM 번호',
ALARM_NAME  VARCHAR(256)  NULL    COMMENT 'ALARM 이름',
ALARM_TYPE  VARCHAR(50)  NULL    COMMENT 'ALARM 타입(E:EMAIL, S:SMS, M:화면)',
ALARM_MAIL_YN  CHAR(1)  NULL    COMMENT '메일 알람 여부',
ALARM_SMS_YN  CHAR(1)  NULL    COMMENT 'SMS 알람 여부',
ALARM_MONITOR_YN  CHAR(1)  NULL    COMMENT '화면 알람 여부',
ALARM_CYCLE  CHAR(1)  NULL    COMMENT 'ALARM 주기(D:매일, H:매시간)',
ALARM_CYCLE_VAL  VARCHAR(50)  NULL    COMMENT '매월, 매주등 부가 옵션에 대한 값(매월 말일, 매월 15일 등, 매주 월,수,금 등)',
ALARM_WEEK  INT(1)  NULL    COMMENT 'ALARM 요일(1-월, 2-화, 3-수, 4-목, 5-금, 6-토, 7-일',
ALARM_TIME  INT(11)  NULL    COMMENT 'ALARM 시간(0~23)',
ALARM_TO  LONGTEXT  NULL    COMMENT '수신자(받는사람)',
ALARM_CC  LONGTEXT  NULL    COMMENT '수신자(참조)',
ALARM_FORM_SEQ  INT(10)  NULL    COMMENT 'ALARM 서식 번호',
ALARM_VAL  LONGTEXT  NULL    COMMENT '검색조건 값',
CTIME  DATETIME  NULL    COMMENT '등록시간',
USER_ID  VARCHAR(30)  NULL    COMMENT '등록자',
USER_NM  VARCHAR(20)  NULL    COMMENT '등록자 이름',
USER_HP  VARCHAR(50)  NULL    COMMENT '등록자 핸드폰 번호',
USE_YN  CHAR(1)  NULL    COMMENT '실행여부',
CSV_YN  CHAR(1)  NULL    COMMENT '메일 첨부 파일 형식',
EXCEL_MAX_CNT  INT(11)  NULL    COMMENT '메일 첨부 엑셀형식 최대 건수',
PRIMARY KEY (ALARM_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='예약 알람 설정';





CREATE TABLE IF NOT EXISTS UI_ALARM_FORM(
FORM_SEQ  INT(10)  NOT NULL    COMMENT '서식 번호',
FORM_SUBJECT  VARCHAR(256)  NULL    COMMENT '서식 제목',
FORM_CONTENT  LONGTEXT  NULL    COMMENT '서식 내용',
FORM_COMMENT  VARCHAR(256)  NULL    COMMENT '서식 설명',
PRIMARY KEY (FORM_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='예약 알람 서식';



CREATE TABLE IF NOT EXISTS UI_ALARM_LOG(
ALARM_LOG_SEQ  INT(11)  NOT NULL    COMMENT 'ALARM 로그 번호',
ALARM_SEQ  INT(11)  NOT NULL    COMMENT 'ALARM 번호',
ETIME  DATETIME  NULL    COMMENT '생성시간',
RMSG  LONGTEXT  NULL    COMMENT '로그 메시지',
RCNT  INT(11)  NULL    COMMENT '실행 결과 건수',
PRIMARY KEY (ALARM_LOG_SEQ, ALARM_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='예약 알람 로그';


CREATE TABLE IF NOT EXISTS UI_UACS_DID(
GROUP_ID  VARCHAR(15)  NOT NULL    COMMENT '그룹 ID',
CODE  VARCHAR(10)  NULL    COMMENT '카테고리 ID',
PCODE  VARCHAR(10)  NULL    COMMENT '상위 카테고리 ID',
GROUP_NM  VARCHAR(128)  NULL    COMMENT '그룹명',
KNAME  VARCHAR(128)  NULL    COMMENT '한글명',
ENAME  VARCHAR(128)  NULL    COMMENT '영어명',
PRIMARY KEY (GROUP_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DID 패턴';


CREATE TABLE IF NOT EXISTS UI_UACS_POLICY_DID(
PID  VARCHAR(30)  NOT NULL    COMMENT '카테고리 ID',
GROUP_ID  VARCHAR(15)  NULL    COMMENT '그룹 ID',
GROUP_NM  VARCHAR(128)  NULL    COMMENT '그룹명',
NAME  VARCHAR(128)  NULL    COMMENT 'DID명',
USEYN  CHAR(1)  NULL    COMMENT '사용여부',
STIME  DATE  NULL    COMMENT '시작일',
ETIME  DATE  NULL    COMMENT '종료일',
SBTIME  VARCHAR(336)  NULL    COMMENT '스케줄',
PERIOD_TYPE  CHAR(1)  NULL    COMMENT '기간 타입(Y:기간 설정, N: 기간 상관없음)',
PTYPE  CHAR(1)  NULL    COMMENT '패턴타입(N: 신규 패턴, D: 삭제된 패턴)',
PRIMARY KEY (PID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DID 정책';


CREATE TABLE IF NOT EXISTS UI_UACS_DID_ICON(
GROUP_ID  VARCHAR(15)  NOT NULL    COMMENT '그룹 ID',
ICON  VARCHAR(256)  NULL    COMMENT '아이콘',
PRIMARY KEY (GROUP_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DID 정책 아이콘';


CREATE TABLE IF NOT EXISTS UI_UACS_POLICY_URL_IP(
PID  VARCHAR(30)  NOT NULL    COMMENT '카테고리 ID',
NAME  VARCHAR(128)  NULL    COMMENT '분류명',
TYPE  CHAR(1)  NULL    COMMENT '정책 타입(U: URL, S: 목적지 IP 차단)',
USEYN  CHAR(1)  NULL    COMMENT '사용여부',
STIME  DATE  NULL    COMMENT '시작일',
ETIME  DATE  NULL    COMMENT '종료일',
SBTIME  VARCHAR(336)  NULL    COMMENT '스케줄',
PORT  VARCHAR(256)  NULL    COMMENT '허용 포트',
PERIOD_TYPE  CHAR(1)  NULL    COMMENT '기간 타입(Y:기간 설정, N: 기간 상관없음)',
PRIMARY KEY (PID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='URL/IP 정책';


CREATE TABLE IF NOT EXISTS UI_UACS_URL(
URL_SEQ  INT(11)  NOT NULL    COMMENT 'URL 일련번호',
PID  VARCHAR(30)  NULL    COMMENT '카테고리 ID',
URL  VARCHAR(255)  NULL    COMMENT '차단 URL',
CTIME  DATETIME  NULL    COMMENT '생성시간',
PRIMARY KEY (URL_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='차단 URL';


CREATE TABLE IF NOT EXISTS UI_UACS_IP(
IP_SEQ  INT(11)  NOT NULL    COMMENT 'IP 일련번호',
PID  VARCHAR(30)  NULL    COMMENT '카테고리 ID',
SIP  VARCHAR(64)  NULL    COMMENT '차단 시작 IP',
EIP  VARCHAR(64)  NULL    COMMENT '차단 끝 IP',
CIDR  INT(5)  NULL    COMMENT '서브넷 마스크',
CIDR_LABEL  VARCHAR(64)  NULL    COMMENT '서브넷 마스크 라벨',
CTIME  DATETIME  NULL    COMMENT '생성시간',
PRIMARY KEY (IP_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='차단 IP';


CREATE TABLE IF NOT EXISTS UI_UACS_TARGET(
TARGET_SEQ  INT(11)  NOT NULL    COMMENT '대상 일련번호',
PID  VARCHAR(30)  NULL    COMMENT '카테고리 ID',
POLICY_TYPE  CHAR(1)  NULL    COMMENT '차단/허용 타입(차단: B, 허용: P)',
SBTYPE  CHAR(1)  NULL    COMMENT '차단유형(I: 단일 IP 주소,  S: 서브넷마스크, U: 사용자, B: 사업장, D: 부서)',
SIP  VARCHAR(64)  NULL    COMMENT '시작 IP',
EIP  VARCHAR(64)  NULL    COMMENT '끝 IP',
CIDR  INT(5)  NULL    COMMENT '서브넷 마스크',
SBCODE  VARCHAR(250)  NULL    COMMENT '차단유형 값',
COMMENT  VARCHAR(250)  NULL    COMMENT '설명',
CTIME  DATETIME  NULL    COMMENT '생성시간',
PRIMARY KEY (TARGET_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='차단 대상';


CREATE TABLE IF NOT EXISTS UI_UACS_BLOCK_MESSAGE(
TYPE  CHAR(1)  NOT NULL    COMMENT '차단 메시지 타입(P: IP차단, U: URL 차단)',
USER_ID  VARCHAR(50)  NULL    COMMENT '관리자 ID',
MESSAGE  LONGTEXT  NULL    COMMENT '차단 메시지',
CTIME  DATETIME  NULL    COMMENT '생성시간',
PRIMARY KEY (TYPE)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='차단 메시지';

CREATE TABLE IF NOT EXISTS UI_MSG_SEARCH_LOG(
	SEARCH_SEQ  INT(11) NOT NULL AUTO_INCREMENT COMMENT '조회 일련번호',
	SEARCH_DT DATETIME NOT NULL COMMENT '조회 일자',
  	SEARCH_TYPE char(1) NOT NULL COMMENT '조회 유형(Y:지정검색, N:미지정 검색)',
	SEARCH_ID  VARCHAR(50)  NOT NULL    COMMENT '조회자 아이디',
	SEARCH_NAME  VARCHAR(50)  NOT NULL    COMMENT '조회자 이름',
	P_FILTER_SEQ  INT(11) COMMENT '상위 필터 시퀀스',
	FILTER_SEQ INT(11) COMMENT '필터 시퀀스',
	FILTER_NM  VARCHAR(128) COMMENT '필터명',
	CONSENT_NO VARCHAR(30)  COMMENT '동의서 번호',
	CONSENT_USER_ID varchar(50) COMMENT '동의서 사용자 아이디',
	CONSENT_NAME varchar(255) COMMENT '동의서 성명',
	CONDITIONS  LONGTEXT  NULL   COMMENT '검색조건 값',
PRIMARY KEY (SEARCH_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='조회이력';

CREATE TABLE IF NOT EXISTS UI_USER_GROUP (
  GROUP_CODE varchar(60) NOT NULL COMMENT '그룹 코드',
  GROUP_NAME varchar(300) DEFAULT NULL COMMENT '그룹명',
  PRIMARY KEY (GROUP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 그룹 코드';


CREATE TABLE IF NOT EXISTS UI_USER_GROUP_LIST (
  GROUP_CODE varchar(60) NOT NULL COMMENT '그룹코드',
  LIST_SEQ int(11) NOT NULL DEFAULT '0' COMMENT '그룹코드 목록 일련번호',
  USER_ID varchar(250) NOT NULL COMMENT '사용자 아이디',
  PRIMARY KEY (GROUP_CODE, LIST_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 그룹 목록';

CREATE TABLE IF NOT EXISTS UI_DOWNLOAD_BATCH(
DOWN_SEQ  INT(11)  NOT NULL  AUTO_INCREMENT  COMMENT '다운로드 일련번호',
EXPORT_TYPE  VARCHAR(10)  NOT NULL    COMMENT '내보내기 유형(L:목록,B:본문,A:첨부파일,LB:목록+본문,LBA:목록+본문+첨부파일)',
EXPORT_FILE_EXT  VARCHAR(10)  NOT NULL    COMMENT '내보내기 파일 확장자(xlsx:엑셀,cell:한셀,csv:텍스트,pdf:목록)',
DOWN_VAL  LONGTEXT  NULL    COMMENT '검색조건 값',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 ID',
REQ_DT  DATETIME  NULL    COMMENT '요청일',
END_DT  DATETIME  NULL    COMMENT '유효기간',
DOWN_STATUS  INT(11)  NULL  DEFAULT '0'  COMMENT '진행상태',
STATUS_STR  CHAR(1)  NULL    COMMENT '상태값(S:시작,I:진행중,Y:파일생성완료,X:삭제됨,E:오류)',
DOWNFILE_PATH  VARCHAR(500)  NULL    COMMENT '다운로드 파일 경로',
DOWNFILE_SIZE  BIGINT UNSIGNED  NULL    COMMENT '다운로드 파일 크기',
ING_ROWS  BIGINT UNSIGNED  NULL  DEFAULT '0'  COMMENT '진행 중 ROW',
TOTAL_ROWS  BIGINT UNSIGNED  NULL  DEFAULT '0'  COMMENT '전체 ROW',
SKIP_ROWS BIGINT UNSIGNED NULL DEFAULT '0' COMMENT 'skip Row',
UPDATE_DT DATETIME NULL COMMENT '상태 Update 시간',
PRIMARY KEY (DOWN_SEQ)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='다운로드 배치';

CREATE TABLE IF NOT EXISTS UI_ADMIN_MENU(
ADMIN_ID  VARCHAR(50)  NOT NULL  COMMENT '운용자 아이디',
AUTH_ID  VARCHAR(256)  NOT NULL  COMMENT '권한 ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 메뉴 권한';

CREATE TABLE IF NOT EXISTS UI_MENU_AUTH(
AUTH_ID  VARCHAR(50)  NOT NULL  COMMENT '권한 ID',
AUTH_NAME  VARCHAR(250)  DEFAULT NULL  COMMENT '권한 명',
P_MENU_ID  VARCHAR(50)  DEFAULT NULL  COMMENT '상위 메뉴 ID',
P_MENU_NAME  VARCHAR(250)  DEFAULT NULL  COMMENT '상위 메뉴 명',
MENU_ID  VARCHAR(50)  NOT NULL  COMMENT '메뉴 ID',
MENU_NAME  VARCHAR(250)  DEFAULT NULL  COMMENT '메뉴 명',
MENU_ORDER  INT(11)  DEFAULT NULL  COMMENT '메뉴순서',
USE_YN  CHAR(1)  DEFAULT 'Y'  COMMENT '사용여부',
PRIMARY KEY (AUTH_ID)     ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='메뉴 권한';



CREATE TABLE IF NOT EXISTS UI_CUSTOM_DASHBOARD(
DASH_KEY  INT(11)  NOT NULL    COMMENT 'DASHBOARD KEY',
DASH_NAME VARCHAR(100) NOT NULL    COMMENT '항목명',
DASH_TYPE  CHAR(1)  NULL    COMMENT 'DASHBOARD 타입(S:단일 건수, D:복합건수, C:차트, L:리스트)',
DASH_MULTI_X  VARCHAR(30)  NULL    COMMENT '복합건수 왼쪽값',
DASH_MULTI_Y  VARCHAR(30)  NULL    COMMENT '복합건수 오른쪽값',
DASH_CHART  VARCHAR(10)  NULL    COMMENT '차트종류',
DASH_CHART_X  VARCHAR(30)  NULL    COMMENT '차트 값 x축',
DASH_CHART_Y  VARCHAR(30)  NULL    COMMENT '차트 값 y축',
DASH_ICON  VARCHAR(30)  NULL    COMMENT 'DASHBOARD 아이콘 CLASS',
DASH_COLOR  VARCHAR(30)  NULL    COMMENT 'DASHBOARD 색상 CLASS',
DASH_HTML LONGTEXT  NULL    COMMENT 'DASHBOARD HTML 데이터',
DASH_CONDITION  LONGTEXT  NULL    COMMENT 'DASHBOARD 조건',
DASH_COMMENT VARCHAR(100) NULL    COMMENT '항목설명',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
USEYN  CHAR(1)  NOT NULL     DEFAULT 'N'   COMMENT '사용여부',
PRIMARY KEY (DASH_KEY) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI CUSTOM 대시보드 항목';

CREATE TABLE IF NOT EXISTS UI_CUSTOM_DASHBOARD_DEFAULT(
DASH_KEY  INT(11)  NOT NULL    COMMENT 'DASHBOARD KEY',
DASH_NAME VARCHAR(100) NOT NULL    COMMENT '항목명',
DASH_TYPE  CHAR(1)  NULL    COMMENT 'DASHBOARD 타입(S:단일 건수, D:복합건수, C:차트, L:리스트)',
DASH_MULTI_X  VARCHAR(30)  NULL    COMMENT '복합건수 왼쪽값',
DASH_MULTI_Y  VARCHAR(30)  NULL    COMMENT '복합건수 오른쪽값',
DASH_CHART  VARCHAR(10)  NULL    COMMENT '차트종류',
DASH_CHART_X  VARCHAR(30)  NULL    COMMENT '차트 값 x축',
DASH_CHART_Y  VARCHAR(30)  NULL    COMMENT '차트 값 y축',
DASH_ICON  VARCHAR(30)  NULL    COMMENT 'DASHBOARD 아이콘 CLASS',
DASH_COLOR  VARCHAR(30)  NULL    COMMENT 'DASHBOARD 색상 CLASS',
DASH_HTML LONGTEXT  NULL    COMMENT 'DASHBOARD HTML 데이터',
DASH_CONDITION  LONGTEXT  NULL    COMMENT 'DASHBOARD 조건',
DASH_COMMENT VARCHAR(100) NULL    COMMENT '항목설명',
USEYN  CHAR(1)  NOT NULL     DEFAULT 'N'   COMMENT '사용여부',
PRIMARY KEY (DASH_KEY) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI CUSTOM 대시보드 항목 템플릿';

CREATE TABLE IF NOT EXISTS UI_CUSTOM_DASHBOARD_SHARE(
DASH_KEY  INT(11)  NOT NULL    COMMENT 'DASHBOARD KEY',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
P_DASH_KEY  INT(11)  NOT NULL    COMMENT '배포 DASHBOARD KEY',
PRIMARY KEY (DASH_KEY) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI CUSTOM 대시보드 배포';

CREATE TABLE IF NOT EXISTS UI_CUSTOM_DASHBOARD_MENU(
MENU_KEY  INT(11)  NOT NULL    COMMENT '메뉴 KEY',
MENU_NAME VARCHAR(100) NOT NULL    COMMENT '메뉴명',
MENU_ICON  VARCHAR(30)  NULL    COMMENT '메뉴 아이콘 CLASS',
ADMIN_ID  VARCHAR(50)  NOT NULL    COMMENT '운용자 아이디',
USEYN  CHAR(1)  NOT NULL  DEFAULT 'Y'   COMMENT '사용여부',
DEFAULT_MENU  CHAR(1)  NULL    COMMENT '최초 접속 시 접속 메뉴',
UPDATE_DT DATETIME NULL COMMENT '수정 날짜',
PRIMARY KEY (MENU_KEY) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI CUSTOM 대시보드 메뉴';

CREATE TABLE IF NOT EXISTS UI_CUSTOM_DASHBOARD_POSITION(
MENU_KEY  INT(11)  NOT NULL    COMMENT '메뉴 KEY',
DASH_KEY  INT(11)  NOT NULL    COMMENT 'DASHBOARD KEY',
DASH_ID  VARCHAR(50)  NULL    COMMENT 'DASHBOARD ID',
DASH_X INT(2) NOT NULL COMMENT '항목 X값 위치',
DASH_Y INT(2) NOT NULL COMMENT '항목 Y값 위치',
DASH_WIDTH INT(2) NULL COMMENT '항목 넓이',
DASH_HEIGHT INT(2) NULL COMMENT '항목 높이',
DASH_MIN_WIDTH INT(2) NULL COMMENT '항목 최소 넓이',
DASH_MIN_HEIGHT INT(2) NULL COMMENT '항목 최소 높이',
DASH_MAX_WIDTH INT(2) NULL COMMENT '항목 최대 넓이',
DASH_MAX_HEIGHT INT(2) NULL COMMENT '항목 최대 높이',
PRIMARY KEY (MENU_KEY, DASH_KEY, DASH_X, DASH_Y) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI CUSTOM 대시보드 위치';

CREATE TABLE IF NOT EXISTS UI_CUSTOM_DASHBOARD_POSITION_DEFAULT(
POSITION_SEQ  INT(11)  NOT NULL    COMMENT '포지션 SEQ',
DASH_X INT(2) NOT NULL COMMENT '항목 X값 위치',
DASH_Y INT(2) NOT NULL COMMENT '항목 Y값 위치',
DASH_WIDTH INT(2) NULL COMMENT '항목 넓이',
DASH_HEIGHT INT(2) NULL COMMENT '항목 높이',
DASH_MIN_WIDTH INT(2) NULL COMMENT '항목 최소 넓이',
DASH_MIN_HEIGHT INT(2) NULL COMMENT '항목 최소 높이',
DASH_MAX_WIDTH INT(2) NULL COMMENT '항목 최대 넓이',
DASH_MAX_HEIGHT INT(2) NULL COMMENT '항목 최대 높이',
PRIMARY KEY (POSITION_SEQ, DASH_X, DASH_Y) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI CUSTOM 대시보드 위치 템플릿';

CREATE TABLE IF NOT EXISTS UI_MENU (
MENU_ID VARCHAR(50) NOT NULL COMMENT '메뉴 아이디',
MENU_DEFAULT_NAME VARCHAR(128) DEFAULT NULL COMMENT '디폴트 메뉴명(언어 properties 파일에서 못찾을시 사용)',
P_MENU_ID VARCHAR(50) DEFAULT NULL COMMENT '상위메뉴 아이디',
PKG_TYPE CHAR(1) DEFAULT NULL COMMENT '제품타입(L:LT/LTH, C:CF, M:LT/LTH+CF)',
MENU_AUTH CHAR(1) DEFAULT NULL COMMENT '메뉴 권한(S:시스템 운용자, M:모니터링 운용자)',
MENU_LINK VARCHAR(512) DEFAULT NULL COMMENT '메뉴 이동링크',
MENU_ICON VARCHAR(50) DEFAULT NULL COMMENT '메뉴 아이콘 아이디',
MENU_ORDER INT(2) DEFAULT NULL COMMENT '정렬순서',
MENU_USEYN CHAR(1) DEFAULT 'Y' COMMENT '사용여부(Y/N)',
PRIMARY KEY (MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='메뉴 관리';

CREATE TABLE IF NOT EXISTS `UI_ADMIN_CEO_GROUP` (
	GROUP_CODE  VARCHAR(60) NOT NULL COMMENT '그룹 코드',
	ADMIN_ID	VARCHAR(50)	NOT NULL,
  PRIMARY KEY (`GROUP_CODE`,`ADMIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='운용자별 CEO 사용자 그룹';

CREATE TABLE IF NOT EXISTS `UI_ADMIN_USER_GROUP` (
	GROUP_SEQ	INT(11)		NOT NULL AUTO_INCREMENT,
	ADMIN_ID	VARCHAR(50)	NOT NULL,
	GROUP_NAME	VARCHAR(60)	DEFAULT NULL,
	GROUP_COLOR	VARCHAR(7)	DEFAULT '#5376A3',
	USE_YN		CHAR(1)		CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`GROUP_SEQ`,`ADMIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='운용자별 사용자 그룹';

CREATE TABLE IF NOT EXISTS `UI_ADMIN_USER_GROUP_LIST` (
	GROUP_SEQ	INT(11)			NOT NULL,
	USER_ID		VARCHAR(250)	NOT NULL,
	PRIMARY KEY (`USER_ID`,`GROUP_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자별 사용자 그룹 사용자 리스트';

CREATE TABLE IF NOT EXISTS `UI_SEARCH_KEYWORD` (
	SK_SEQ		INT(11) NOT NULL AUTO_INCREMENT COMMENT '검색어 일련번호',
	ADMIN_ID	varchar(50) NOT NULL COMMENT '운용자 아이디',
	SEARCH_KEYWORD	varchar(500) NOT NULL COMMENT '검색한 검색어',
	CREATE_DT	datetime DEFAULT NULL COMMENT '생성일',
  PRIMARY KEY (`SK_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자별 검색어 저장';



CREATE TABLE IF NOT EXISTS `UI_EPMSG_TYPE` (
  `EPMSG_TYPE_CODE` varchar(50) NOT NULL COMMENT 'knox 메일 종류 코드',
  `EPMSG_TYPE_NAME` varchar(300) NOT NULL COMMENT 'knox 메일 종류 이름',
  `EPMSG_TYPE_COLOR` varchar(7) DEFAULT '#5376A3' COMMENT 'knox 메일 종류 색상',
  PRIMARY KEY (`EPMSG_TYPE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='knox 메일 종류 코드';


CREATE TABLE IF NOT EXISTS `INFO_AUDIT` (
  `DATE` datetime NOT NULL COMMENT '날짜',
  `ADMIN_ID` varchar(50) NOT NULL COMMENT '운용자 ID',
  `SEQ` bigint(20) unsigned NOT NULL COMMENT '감사로그 Seq',
  `PRODUCT` varchar(50) DEFAULT NULL COMMENT '제품',
  `CATEGORY` varchar(255) DEFAULT NULL COMMENT '제품',
  `OPERATION` varchar(20) DEFAULT NULL COMMENT '행위',
  `ADMIN_NAME` varchar(255) DEFAULT NULL COMMENT '운용자 이름',
  `ADMIN_IP` varchar(64) DEFAULT NULL COMMENT '운용자 IP',
  `MENU_ID` varchar(50) DEFAULT NULL COMMENT '메뉴 ID',
  `P_MENU_ID` varchar(50) DEFAULT NULL COMMENT '상위 메뉴 ID',
  `INFORMATION` longtext COMMENT '정보',
  `COMMENTS` varchar(500) DEFAULT NULL COMMENT '상위 메뉴 ID',
  PRIMARY KEY (`DATE`,`ADMIN_ID`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='운용자 감사로그';




