package com.xcurenet.audit.service;

public enum Menu {

	CONNECTION("CONNECTION"),
	DASHBOARD("DASHBOARD"),
	DASHBOARD_MENU("DASHBOARD_MENU"),
	DASHBOARD_SETUP("DASHBOARD_SETUP"),
	MESSAGE_INFO("MESSAGE_INFO"),
	MESSAGE_SERVICE("MESSAGE_SERVICE"),
	INTEREST_USER("INTEREST_USER"),
	STAT_USER("STAT_USER"),
	STAT_INTEREST("STAT_INTEREST"),
	STAT_SENDER("STAT_SENDER"),
	STAT_SVC("STAT_SVC"),
	STAT_KWD("STAT_KWD"),
	STAT_ATTACHTYPE("STAT_ATTACHTYPE"),
	STAT_ATTACHNAME("STAT_ATTACHNAME"),
	STAT_URL("STAT_URL"),
	STAT_ADMINREAD ("STAT_ADMINREAD"),
	STAT_DEVTRAFFIC("STAT_DEVTRAFFIC"),
	STAT_OCR("STAT_OCR"),
	STAT_REPORT("STAT_REPORT"),
	RESERVATION_ALARM("RESERVATION_ALARM"),
	KEYWORD_MGMT("KEYWORD_MGMT"),
	RELATION_KEYWORD("RELATION_KEYWORD"),
	RELATION_PATTERN("RELATION_PATTERN"),
	CONSENT_MGMT("CONSENT_MGMT"),
	ANALYSIS_RELATION("ANALYSIS_RELATION"),
	ANALYSIS_FLUCTUATION ("ANALYSIS_FLUCTUATION"),
	ANALYSIS_CUSTOM("ANALYSIS_CUSTOM"),
	ANALYSIS_INFO("ANALYSIS_INFO"),
	POLICY_NOLOG("POLICY_NOLOG"),
	POLICY_DID("POLICY_DID"),
	POLICY_URLIP("POLICY_URLIP"),
	BLOCK_DID("BLOCK_DID"),
	BLOCK_URL("BLOCK_URL"),
	BLOCK_IP("BLOCK_IP"),
	DEV_INFO("DEV_INFO"),
	DEV_EVENTLOG("DEV_EVENTLOG"),
	ORG_MGMT("ORG_MGMT"),
	USER_MGMT("USER_MGMT"),
	USER_GROUP_MGMT("USER_GROUP_MGMT"),
	BUSI_IPRANGE("BUSI_IPRANGE"),
	DEPT_IPRANGE("DEPT_IPRANGE"),
	CODE_INFO("CODE_INFO"),
	ADMIN_MGMT("ADMIN_MGMT"),
	HOLIDAY_BUSI("HOLIDAY_BUSI"),
	HOLIDAY_LEGAL("HOLIDAY_LEGAL"),
	SEARCH_LOG("SEARCH_LOG"),
	AUDIT_LOG("AUDIT_LOG"),

	EMPTY("");

	private String menuId;

	Menu(String arg) {
		this.menuId = arg;
	}

	public String getMenuId() {
		return this.menuId;
	}
}