#!/bin/sh

### BEGIN INIT INFO
# Provides:          EMASS AI v1 UI
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Controls EMASS AI UI as a Service
### END INIT INFO

INSTALL_DIR="/users/emassai"

if [ ! -d "$INSTALL_DIR" ]; then
  echo "$INSTALL_DIR not found! Please check the INSTALL_DIR setting in your $0 script."
  exit 1
fi

case "$1" in
  start|stop|restart|status)
    SOLR_CMD="$1"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit
esac

"$INSTALL_DIR/bin/emassai" "$SOLR_CMD"

